export const cs = {
  addColumnAfter: "Vložit sloupec za",
  addColumnBefore: "Vložit sloupec před",
  addRowAfter: "Vložit řádku za",
  addRowBefore: "Vložit řádku před",
  alignCenter: "Zarovnat doprostřed",
  alignLeft: "Zarovnat doleva",
  alignRight: "Zarovnat doprava",
  bulletList: "Seznam s odrážkami",
  checkboxList: "Seznam s úkoly",
  codeBlock: "Kód",
  codeCopied: "Zkopírováno",
  codeInline: "Kód",
  createLink: "Vytvořit odkaz",
  createLinkError: "Něco se pokazilo",
  createNewDoc: "Vytvořit nový dokument",
  deleteColumn: "Smazat sloupec",
  deleteRow: "Smazat řádek",
  deleteTable: "Smazat tabulku",
  deleteImage: "Smazat obrázek",
  alignImageLeft: "Zarovnat doleva na půl stránky",
  alignImageRight: "Zarovnat doprava na půl stránky",
  alignImageDefault: "Doprostřed",
  em: "Italic",
  embedInvalidLink: "Toto nebude fungovat",
  findOrCreateDoc: "Najít a nebo vytvořit dokument",
  h1: "Velký nadpis",
  h2: "Střední nadpis",
  h3: "Malý nadpis",
  heading: "Nadpis",
  hr: "Oddělovač",
  image: "Obrázek",
  imageUploadError: "Při narávání obrázku se něco pokazilo",
  info: "Info",
  infoNotice: "Informační zpráva",
  link: "Odkaz",
  linkCopied: "Odkaz zkopirován",
  mark: "Zvýraznit",
  newLineEmpty: "Napište '/' pro vložení...",
  newLineWithSlash: "Pokračujte psát pro filtrování…",
  noResults: "Žádné výsledky",
  openLink: "Otevřít odkaz",
  orderedList: "Číselný seznam",
  pasteLink: "Vložit odkaz…",
  pasteLinkWithTitle: (title: string) => `Vložit ${title} odkaz...`,
  placeholder: "Placeholder",
  quote: "Citát",
  removeLink: "Smazat odkaz",
  searchOrPasteLink: "Vyledat nebo vložit odkaz…",
  strikethrough: "Přeškrtnuté",
  strong: "Tučné",
  subheading: "Podnadpis",
  table: "Tabulka",
  tip: "Tip",
  tipNotice: "Tip",
  warning: "Upozornění",
  warningNotice: "Upozornění",
};

export default cs;
